name: Ratchet

on:
  push:
    branches:
      - 'dependabot/github_actions/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/sethvargo/ratchet:0.2.0
    name: ratchet
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
      - run: /ratchet pin ./.github/workflows/test.yml
      - run: cat ./.github/workflows/test.yml
      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
